# Generated by Django 2.0.8 on 2018-08-02 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-start_time',), 'permissions': (('tracking_view_visitor', 'Can view visitor for django-tracking2'),)},
        ),
    ]
