# Generated by Django 2.1.14 on 2020-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20180802_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='method',
            field=models.CharField(db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='url',
            field=models.TextField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='pageview',
            name='view_time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
