# Generated by Django 4.0.4 on 2022-10-11 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200623_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='end_time',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
